
spring:
  application:
    name: StockDividend


  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    defer-datasource-initialization: true
    database: H2
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: emVyb2Jhc2Utc3ByaW5nLWJvb3QtcHJvamVjdC1kaXZpZGVuZAo=


logging:
  level:
    root: info

scheduler:
  scrap:
    yahoo: "0 0 0 1 * *"

