spring:
  application:
    name: user-api
  cloud:
    openfeign:
      okhttp:
        enabled: true
      autoconfiguration:
        jackson:
          enabled: true

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/cms-mysql?use-SSL=false&useUnicode=true&allowPublicKeyRetrieval=true
#      username: cms
#      password: cms


#test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      username: sa
      password:





