spring:
  application:
    name: user-api
  cloud:
    openfeign:
      okhttp:
        enabled: true
      autoconfiguration:
        jackson:
          enabled: true

  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cms?use-SSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: cms
    password: cms


#test

#  datasource:
#    driver-class-name: org.h2.Driver
#    hikari:
#      jdbc-url: jdbc:h2:tcp://localhost/~/test
#      username: sa
#      password:





