server:
  shutdown: graceful
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zeroorder?use-SSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: cms
    password: cms
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  data:
    redis:
      port: 6379

  jackson:
    serialization.FAIL_ON_EMPTY_BEANS: false
    deserialization.FAIL_ON_UNKNOWN_PROPERTIES: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

user-api:
  feign:
    client:
      url: localhost:8080
