server:
  shutdown: graceful
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zeroorder?use-SSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: cms
    password: cms
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  data:
    redis:
      port: 6379
